version: '3.9'

services:
  some-project-one-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: server
        BUILD_PROJECT: some-project-one
        VERSION: v1.2.7

  some-project-two-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: server
        BUILD_PROJECT: some-project-two
        VERSION: v1.2.7

  some-project-one-consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: consumer
        BUILD_PROJECT: some-project-one
        VERSION: v1.2.7

  some-project-two-consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: consumer
        BUILD_PROJECT: some-project-two
        VERSION: v1.2.7