version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: server
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: consumer